== ri-storage-twitter image:https://img.shields.io/badge/License-EPL%202.0-blue.svg["EPL 2.0", link="https://www.eclipse.org/legal/epl-2.0/"]

This service was created as a result of the OpenReq project funded by the European Union Horizon 2020 Research and Innovation programme under grant agreement No 732463.

== Technical description
=== What does the microservice do
The ri-storage-twitter microservice represents an interface to a database persisting all JSON objects related to Twitter data. It can store tweets, Twitter accounts that should be observed by the link:https://github.com/OpenReqEU/ri-orchestration-twitter[ri-orchestration-twitter] ms. It also returns tweets and observed accounts.

=== Which technologies are used
- Go (-> https://github.com/golang/go)
- Gorilla Mux (-> https://github.com/gorilla/mux)
- MongoDB (-> https://www.mongodb.com/)

=== How to install it
Run the following commands to start the microservice:

. docker build -t ri-storage-twitter .
. docker run -e "MONGO_IP=<mydbip>" -p 9682:9682 ri-storage-twitter

The IP adresss of the Mongo Database in which to store Twitter data is passed through the environment variable MONGO_IP.
<mydbip> should be set by the IP adress of your database.

=== How to use it (high-level description)
The API is documented by using Swagger2:

- link:http://217.172.12.199/registry/#/services/ri-storage-twitter[Rendered Documentation]

=== Notes for developers 
None.

=== Sources
None.


== How to contribute
See OpenReq project contribution link:https://github.com/OpenReqEU/OpenReq/blob/master/CONTRIBUTING.md[Guidlines]

== License
Free use of this software is granted under the terms of the EPL version 2 (EPL2.0).